language: cpp
compiler: clang
before script:  
  - sudo apt-get install libboost-asio-dev -y
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
script:
- cmake .
- cmake --build .
- cmake --build . --target package
deploy:
- provider: script
  skip_cleanup: true
  script:
  - curl -T bulk_server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -usmart-roger:$BINTRAY_API_KEY "https://api.bintray.com/content/smart-roger/Otus_cpp/bulk_server/$TRAVIS_BUILD_NUMBER/bulk_server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1" 
